/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { core } from "nexus"
declare global {
  interface NexusGenCustomInputMethods<TypeName extends string> {
    /**
     * The `Upload` scalar type represents a file upload.
     */
    upload<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "Upload";
  }
}
declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    /**
     * The `Upload` scalar type represents a file upload.
     */
    upload<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "Upload";
  }
}


declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  Upload: any
}

export interface NexusGenObjects {
  ChatRoom: { // root type
    createdAt: string; // String!
    id: string; // String!
    messages?: Array<NexusGenRootTypes['Message'] | null> | null; // [Message]
    updatedAt: string; // String!
    user?: Array<NexusGenRootTypes['User'] | null> | null; // [User]
  }
  GlobalResult: { // root type
    error?: string | null; // String
    ok: boolean; // Boolean!
  }
  Hashtag: { // root type
    createdAt: string; // String!
    hashtag: string; // String!
    id: string; // String!
    updatedAt: string; // String!
  }
  Message: { // root type
    createdAt: string; // String!
    id: string; // String!
    payload: string; // String!
    room: NexusGenRootTypes['ChatRoom']; // ChatRoom!
    updatedAt: string; // String!
    user: NexusGenRootTypes['User']; // User!
  }
  Mutation: {};
  Product: { // root type
    age?: number | null; // Int
    brand?: string | null; // String
    category: string; // String!
    color: string; // String!
    condition: string; // String!
    createdAt: string; // String!
    description?: string | null; // String
    discountPrice?: number | null; // Float
    domesticShippingCharge?: number | null; // Int
    id: string; // String!
    isFreeShipping: boolean; // Boolean!
    isWorldWideShipping: boolean; // Boolean!
    location: string; // String!
    name: string; // String!
    photos: Array<string | null>; // [String]!
    price: number; // Float!
    size: string; // String!
    updatedAt: string; // String!
    worldwideShippingCharge?: number | null; // Int
  }
  Query: {};
  SeeFollowerResult: { // root type
    error?: string | null; // String
    followers?: Array<NexusGenRootTypes['User'] | null> | null; // [User]
    ok: boolean; // Boolean!
    totalPages?: number | null; // Int
  }
  SeeFollowingResult: { // root type
    error?: string | null; // String
    following?: Array<NexusGenRootTypes['User'] | null> | null; // [User]
    ok: boolean; // Boolean!
  }
  SigninWithTokenResult: { // root type
    error?: string | null; // String
    ok: boolean; // Boolean!
    token?: string | null; // String
  }
  SignupResult: { // root type
    error?: string | null; // String
    errorType?: string | null; // String
    ok: boolean; // Boolean!
  }
  User: { // root type
    avatar?: string | null; // String
    bio?: string | null; // String
    createdAt: string; // String!
    email: string; // String!
    firstName?: string | null; // String
    followers?: Array<NexusGenRootTypes['User'] | null> | null; // [User]
    following?: Array<NexusGenRootTypes['User'] | null> | null; // [User]
    id: string; // String!
    password: string; // String!
    updatedAt: string; // String!
    username: string; // String!
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  ChatRoom: { // field return type
    createdAt: string; // String!
    id: string; // String!
    messages: Array<NexusGenRootTypes['Message'] | null> | null; // [Message]
    updatedAt: string; // String!
    user: Array<NexusGenRootTypes['User'] | null> | null; // [User]
  }
  GlobalResult: { // field return type
    error: string | null; // String
    ok: boolean; // Boolean!
  }
  Hashtag: { // field return type
    createdAt: string; // String!
    hashtag: string; // String!
    id: string; // String!
    products: Array<NexusGenRootTypes['Product'] | null> | null; // [Product]
    totalProducts: number | null; // Int
    updatedAt: string; // String!
  }
  Message: { // field return type
    createdAt: string; // String!
    id: string; // String!
    payload: string; // String!
    room: NexusGenRootTypes['ChatRoom']; // ChatRoom!
    updatedAt: string; // String!
    user: NexusGenRootTypes['User']; // User!
  }
  Mutation: { // field return type
    createAccount: NexusGenRootTypes['GlobalResult'] | null; // GlobalResult
    editProfile: NexusGenRootTypes['GlobalResult'] | null; // GlobalResult
    followUser: NexusGenRootTypes['GlobalResult'] | null; // GlobalResult
    searchUsers: Array<NexusGenRootTypes['User'] | null> | null; // [User]
    sendMessage: NexusGenRootTypes['GlobalResult'] | null; // GlobalResult
    signin: NexusGenRootTypes['SigninWithTokenResult'] | null; // SigninWithTokenResult
    unfollowUser: NexusGenRootTypes['GlobalResult'] | null; // GlobalResult
    uploadProduct: NexusGenRootTypes['Product'] | null; // Product
  }
  Product: { // field return type
    age: number | null; // Int
    brand: string | null; // String
    category: string; // String!
    color: string; // String!
    condition: string; // String!
    createdAt: string; // String!
    description: string | null; // String
    discountPrice: number | null; // Float
    domesticShippingCharge: number | null; // Int
    hashtags: Array<NexusGenRootTypes['Hashtag'] | null> | null; // [Hashtag]
    id: string; // String!
    isFreeShipping: boolean; // Boolean!
    isWorldWideShipping: boolean; // Boolean!
    location: string; // String!
    name: string; // String!
    photos: Array<string | null>; // [String]!
    price: number; // Float!
    size: string; // String!
    updatedAt: string; // String!
    user: NexusGenRootTypes['User'] | null; // User
    worldwideShippingCharge: number | null; // Int
  }
  Query: { // field return type
    isMyself: NexusGenRootTypes['User'] | null; // User
    seeFollowers: NexusGenRootTypes['SeeFollowerResult'] | null; // SeeFollowerResult
    seeFollowings: NexusGenRootTypes['SeeFollowingResult'] | null; // SeeFollowingResult
    seeHashtag: NexusGenRootTypes['Hashtag'] | null; // Hashtag
    seeProduct: NexusGenRootTypes['Product'] | null; // Product
    seeProfile: NexusGenRootTypes['User'] | null; // User
    seeRoom: NexusGenRootTypes['ChatRoom'] | null; // ChatRoom
    seeRooms: Array<NexusGenRootTypes['ChatRoom'] | null> | null; // [ChatRoom]
  }
  SeeFollowerResult: { // field return type
    error: string | null; // String
    followers: Array<NexusGenRootTypes['User'] | null> | null; // [User]
    ok: boolean; // Boolean!
    totalFollower: number | null; // Int
    totalPages: number | null; // Int
  }
  SeeFollowingResult: { // field return type
    error: string | null; // String
    following: Array<NexusGenRootTypes['User'] | null> | null; // [User]
    ok: boolean; // Boolean!
    totalFollowing: number | null; // Int
  }
  SigninWithTokenResult: { // field return type
    error: string | null; // String
    ok: boolean; // Boolean!
    token: string | null; // String
  }
  SignupResult: { // field return type
    error: string | null; // String
    errorType: string | null; // String
    ok: boolean; // Boolean!
  }
  User: { // field return type
    avatar: string | null; // String
    bio: string | null; // String
    createdAt: string; // String!
    email: string; // String!
    firstName: string | null; // String
    followers: Array<NexusGenRootTypes['User'] | null> | null; // [User]
    following: Array<NexusGenRootTypes['User'] | null> | null; // [User]
    id: string; // String!
    isFollowing: boolean; // Boolean!
    isMyself: boolean; // Boolean!
    password: string; // String!
    totalFollower: number; // Int!
    totalFollowing: number; // Int!
    updatedAt: string; // String!
    username: string; // String!
  }
}

export interface NexusGenFieldTypeNames {
  ChatRoom: { // field return type name
    createdAt: 'String'
    id: 'String'
    messages: 'Message'
    updatedAt: 'String'
    user: 'User'
  }
  GlobalResult: { // field return type name
    error: 'String'
    ok: 'Boolean'
  }
  Hashtag: { // field return type name
    createdAt: 'String'
    hashtag: 'String'
    id: 'String'
    products: 'Product'
    totalProducts: 'Int'
    updatedAt: 'String'
  }
  Message: { // field return type name
    createdAt: 'String'
    id: 'String'
    payload: 'String'
    room: 'ChatRoom'
    updatedAt: 'String'
    user: 'User'
  }
  Mutation: { // field return type name
    createAccount: 'GlobalResult'
    editProfile: 'GlobalResult'
    followUser: 'GlobalResult'
    searchUsers: 'User'
    sendMessage: 'GlobalResult'
    signin: 'SigninWithTokenResult'
    unfollowUser: 'GlobalResult'
    uploadProduct: 'Product'
  }
  Product: { // field return type name
    age: 'Int'
    brand: 'String'
    category: 'String'
    color: 'String'
    condition: 'String'
    createdAt: 'String'
    description: 'String'
    discountPrice: 'Float'
    domesticShippingCharge: 'Int'
    hashtags: 'Hashtag'
    id: 'String'
    isFreeShipping: 'Boolean'
    isWorldWideShipping: 'Boolean'
    location: 'String'
    name: 'String'
    photos: 'String'
    price: 'Float'
    size: 'String'
    updatedAt: 'String'
    user: 'User'
    worldwideShippingCharge: 'Int'
  }
  Query: { // field return type name
    isMyself: 'User'
    seeFollowers: 'SeeFollowerResult'
    seeFollowings: 'SeeFollowingResult'
    seeHashtag: 'Hashtag'
    seeProduct: 'Product'
    seeProfile: 'User'
    seeRoom: 'ChatRoom'
    seeRooms: 'ChatRoom'
  }
  SeeFollowerResult: { // field return type name
    error: 'String'
    followers: 'User'
    ok: 'Boolean'
    totalFollower: 'Int'
    totalPages: 'Int'
  }
  SeeFollowingResult: { // field return type name
    error: 'String'
    following: 'User'
    ok: 'Boolean'
    totalFollowing: 'Int'
  }
  SigninWithTokenResult: { // field return type name
    error: 'String'
    ok: 'Boolean'
    token: 'String'
  }
  SignupResult: { // field return type name
    error: 'String'
    errorType: 'String'
    ok: 'Boolean'
  }
  User: { // field return type name
    avatar: 'String'
    bio: 'String'
    createdAt: 'String'
    email: 'String'
    firstName: 'String'
    followers: 'User'
    following: 'User'
    id: 'String'
    isFollowing: 'Boolean'
    isMyself: 'Boolean'
    password: 'String'
    totalFollower: 'Int'
    totalFollowing: 'Int'
    updatedAt: 'String'
    username: 'String'
  }
}

export interface NexusGenArgTypes {
  Hashtag: {
    products: { // args
      page: number; // Int!
    }
  }
  Mutation: {
    createAccount: { // args
      email: string; // String!
      firstName: string; // String!
      password: string; // String!
      username: string; // String!
    }
    editProfile: { // args
      avatar?: NexusGenScalars['Upload'] | null; // Upload
      bio?: string | null; // String
      email?: string | null; // String
      firstName?: string | null; // String
      password?: string | null; // String
    }
    followUser: { // args
      username: string; // String!
    }
    searchUsers: { // args
      keyword: string; // String!
    }
    sendMessage: { // args
      chatRoomId?: string | null; // String
      payload: string; // String!
      userId?: string | null; // String
    }
    signin: { // args
      password: string; // String!
      username: string; // String!
    }
    unfollowUser: { // args
      username: string; // String!
    }
    uploadProduct: { // args
      age?: number | null; // Int
      brand?: string | null; // String
      category: string; // String!
      color: string; // String!
      condition: string; // String!
      description: string; // String!
      discountPrice?: number | null; // Float
      domesticShippingCharge?: number | null; // Float
      isFreeShipping: boolean; // Boolean!
      isWorldWideShipping: boolean; // Boolean!
      location: string; // String!
      name: string; // String!
      photos?: Array<NexusGenScalars['Upload'] | null> | null; // [Upload]
      price: number; // Float!
      size?: string | null; // String
      worldwideShippingCharge?: number | null; // Float
    }
  }
  Query: {
    seeFollowers: { // args
      page: number; // Int!
      username: string; // String!
    }
    seeFollowings: { // args
      cursor?: number | null; // Int
      username: string; // String!
    }
    seeHashtag: { // args
      hashtag: string; // String!
    }
    seeProduct: { // args
      id: string; // String!
    }
    seeProfile: { // args
      username: string; // String!
    }
    seeRoom: { // args
      id: string; // String!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = never;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: any;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}